### ISSUE TITLE
Child Partition Names

### ISSUE THREAD

**Issue by esb** [rkrage/pg_party#16]
Just found this gem, and it looks like an excellent start to help manage partitions under PGSQL 10.

There are a couple of suggestions that I have. I have decided to use pg_partman to help manage my native child partitions, and this extension automatically creates a pool of new partitions before I need them.

The partitions are named "master_table_p0", "master_table_p1" etc based on the single value in my range that I am using as the partition key.

It would be nice in pg_party if I could provide the name of the partition when creating child partitions so that I can keep the same convention. The name convention will also help me manage old partitions that I no longer need.

Also, creating a child partition does not seem to allow for the use of a template table so that the indexes can be copied and built on the new partition.

**Comment by rkrage** [comment]
Hi there,

As far as partition naming goes, that feature already exists. It's just poorly documented :(

Here's an example from the [schema.rb](https://github.com/rkrage/pg_party/blob/98334ca5679d591ee7760f887c0edbdff15b4b16/spec/internal/db/schema.rb) in the test Rails app:

```ruby
create_range_partition_of :bigint_date_ranges,
  name: :bigint_date_ranges_a,
  partition_key: "created_at::date",
  start_range: Date.today,
  end_range: Date.tomorrow
```

For index creation, `pg_party` only assumes that you want an index on the partition key: https://github.com/rkrage/pg_party/blob/98334ca5679d591ee7760f887c0edbdff15b4b16/lib/pg_party/adapter_decorator.rb#L103

To copy indexes and constraints from a template table, the only workaround I can think of is to create the table using raw SQL, and then attach it to the partitioned table:

```ruby
class MyMigration < ActiveRecord::Migration[5.1]
  def up
    execute(<<-SQL)
      CREATE TABLE master_table_p0
      LIKE some_template
      INCLUDING ALL
    SQL

    attach_partition(:master_table, :master_table_p0)
  end
end
```

If you don't want to go that route, I think you'll just have to manually add the indexes on each child partition for now. I really like your template table idea, though! I'm going to close this issue out and create a new one for that feature.
