### ISSUE TITLE
Create child partitions from template tables

### ISSUE THREAD

**Issue by rkrage** [rkrage/pg_party#17]
It might make sense to add functionality to `create_range_partition_of` and `create_list_partition_of` to create child partitions from template tables. This would be useful to copy over indexes and constraints.

**Comment by justinperkins** [comment]
Do you have a timeline or plan for cutting a new version of the gem?

**Comment by rkrage** [comment]
There's only a few things left in the milestone: documentation (#33) and query support for complex partition keys (#34). Once those are done, I think we're ready for 1.0.0. I'm hoping to cut the release in about a week or so
