### ISSUE TITLE
[Question] [Enhancement] - Partitioning an existing table and creating new paritions

### ISSUE THREAD

**Issue by ohaddahan** [rkrage/pg_party#18]
I want to take a large table I have and split it per user.
Is it possible to:
1. Migrate a table into a partitioned table? ( Even if need to create a new one )
2. Since new users will come and go , is there support to create a new table when a new user is created?

**Comment by rkrage** [comment]
Hi @ohaddahan,

Thank you for the questions. These operations aren't currently built-in, but aren't terribly difficult to accomplish.

> 1. Migrate a table into a partitioned table? ( Even if need to create a new one )

This is a pretty simple feature to add. But in the meantime, just create your partition table first, then copy the data using SQL:

```sql
INSERT INTO partition_table
SELECT * FROM old_table;
```

Or, if there's a small amount of data, you could probably just use Rails:

```ruby
OldTable.all.each { |record| PartitionTable.create!(record.attributes) }
```

> 2. Since new users will come and go , is there support to create a new table when a new user is created?

I'll investigate this further, but I think it'll be very difficult to implement auto-partitioning for all use cases. For this specific scenario, you could try something like this:

```ruby
user_item = UserItem.new(user_id: 1)

begin
  user_item.save!
rescue ActiveRecord::StatementInvalid => e
  if e.message =~ /no partition of relation/
    UserItem.create_partition(values: user_item.user_id)
    user_item.save!
  else
    raise e
  end
end
```

**Comment by ohaddahan** [comment]
@rkrage thanks for commenting this seems promising.
I'll look deeper into this.

**Comment by rkrage** [comment]
@ohaddahan sounds good!

Feel free to send me some concrete code snippets if you need more help!

**Comment by rkrage** [comment]
Sounds like this is resolved. Closing.
