### ISSUE TITLE
Create a sample app or clear instructions

### ISSUE THREAD

**Issue by igorkasyanchuk** [rkrage/pg_party#19]
Hello,
It would be nice to create a simple tutorial or whole sample app. 
Currently, it's not clear how to use work with it. Plus it can bring more people to use this gem
Thanks

**Comment by rkrage** [comment]
Hi @igorkasyanchuk,

Yes, better documentation is in progress. There is (sort of) a sample app that's used in the integration tests.

Here's an example of how you'd use the migrations: https://github.com/rkrage/pg_party/blob/8f326b511e1f6a035a88d86d27af3aa07423de6e/spec/internal/db/schema.rb

And the integration tests that exercise these tables: https://github.com/rkrage/pg_party/tree/8f326b511e1f6a035a88d86d27af3aa07423de6e/spec/integration/model

**Comment by rkrage** [comment]
Will likely be tackled in #33
