### ISSUE TITLE
Missing in db/schema.rb

### ISSUE THREAD

**Issue by hadmut** [rkrage/pg_party#22]
Hi, 
I'm just trying and playing around with it, and I found, that the migrations creating partitions are missing in db/schema.rb, thus the database cannot be recreated with the common rails tools.

**Comment by rkrage** [comment]
Hi @hadmut,

That is a known limitation of this library. Please use the `:sql` schema format:

```ruby
# config/application.rb

config.active_record.schema_format = :sql
```
