### ISSUE TITLE
How to list partition tables?

### ISSUE THREAD

**Issue by hadmut** [rkrage/pg_party#23]
Hi, 

I just wonder how to check if a partition table for a given range exists. 

The Readme describes the SomeRangeRecord.partitions functions, which gives just cryptic table names, but not telling for which ranges they were created. 

What is the recommended way to insert some value if it is unknown whether a partition table exists for that range? Catch an exception, create a partition, and retry?

**Comment by rkrage** [comment]
Programmatically, there isn't currently a way to figure out the range for a given partition. From a psql console, though, you should be able to see attached partitions and their associated metadata:

```
psql=# \d+ bigint_date_ranges

   Column   |            Type             | Collation | Nullable |                    Default                     | Storage | Stats target | Description
------------+-----------------------------+-----------+----------+------------------------------------------------+---------+--------------+-------------
 id         | bigint                      |           | not null | nextval('bigint_date_ranges_id_seq'::regclass) | plain   |              |
 created_at | timestamp without time zone |           | not null |                                                | plain   |              |
 updated_at | timestamp without time zone |           | not null |                                                | plain   |              |
Partition key: RANGE (((created_at)::date))
Partitions: bigint_date_ranges_a FOR VALUES FROM ('2018-03-26') TO ('2018-03-27'),
            bigint_date_ranges_b FOR VALUES FROM ('2018-03-27') TO ('2018-03-28')
```

Also, keep in mind that it is possible to manually name your child partitions to avoid these cryptic names:

```ruby
create_range_partition_of \
  :some_range_records,
  name: :some_range_records_descriptive_partition_name,
  partition_key: "created_at::date",
  start_range: current_date,
  end_range: current_date + 1.day
```

Generally, it's a good idea to create necessary partitions ahead of time (via cron or some other scheduling service). As far as automatic partition creation goes, that isn't natively supported but can be accomplished with the rescuing you described. Example:

```ruby
user_item = UserItem.new(user_id: 1)

begin
  user_item.save!
rescue ActiveRecord::StatementInvalid => e
  if e.message =~ /no partition of relation/
    UserItem.create_partition(values: user_item.user_id)
    user_item.save!
  else
    raise e
  end
end
```
