### ISSUE TITLE
Schema file contains partion tables

### ISSUE THREAD

**Issue by justinperkins** [rkrage/pg_party#36]
When migrations are run and a new schema.sql file is generated, it contains the user-created partition tables for any partitions in the database. This is expected, but also seems wrong since in a multi-dev environment, there will be constant differences in this file since everyone will have different partitions.

Perhaps there's a way to instruct the schema generator to only dump the master partition record.

**Comment by rkrage** [comment]
That's a good call out. In the short term, maybe it makes sense to mention this in the readme? If your partitions are dynamic (time/date based), we can recommend that only the top-level partitioned table is defined in a migration. Individual partitions can be created in the seed file? Off the top of my head, I'm unsure what stage the structure dump happens. I _don't think_ it happens after a `db:seed`, but I can do some digging.

**Comment by justinperkins** [comment]
Also, not sure if you've run into this, but we have to manually create partitions before our tests run. Fixtures don't instead into partitions.

**Comment by rkrage** [comment]
I believe fixtures are transactional by default. Could that be the culprit here?

**Comment by justinperkins** [comment]
I assumed it was because the fixtures do straight inserts, bypassing the model completely. So any model-level callbacks that are setup to create partitions before a new record is inserted will not run.

**Comment by rkrage** [comment]
Could you provide some code snippets?

**Comment by justinperkins** [comment]
Sure, what would you like to see? In my case I have a fixture file for my partitioned model, but the records are not created in my test env unless I create the expected partitions in advance.

**Comment by rkrage** [comment]
Actually, I just dug into the rails source. It appears fixtures are inserted in bulk using `execute`:

https://github.com/rails/rails/blob/5-2-stable/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb#L394

From a rails perspective, there's not much that can be done. Triggers are the only thing that comes to mind, but that seems a bit heavy-handed.

I'll dig into the `structure.sql` issue this weekend.

**Comment by rkrage** [comment]
I guess another suggestion would be to avoid fixtures altogether and use [factory_bot](https://github.com/thoughtbot/factory_bot).
