### ISSUE TITLE
Multiple Key Partition

### ISSUE THREAD

**Issue by RaresSalcudean** [rkrage/pg_party#37]
Hello,

Currently, I'm trying to define a 3 key range partition, but I can't make it work (in terms of PostgreSQL query).

First of all the code:

`

    create_range_partition_of \
      :scores,
      name: "scores_2007".to_sym,
      partition_key: ->{ "recent, deleted, played_at" },
      start_range: [false, false, "1980-01-01"],
      end_range: [false, false, "2008-01-01"]

`

It all works, the partitions get created and I can see them in PGAdmin, but when running a query that is expected to select a certain partition it does not work.

`explain select * from scores where recent = false and deleted = false and played_at = DATE '2006-03-03'` - It checks on all partitions.

However, if I only do a 2 key range partition all works fine.

`

    create_range_partition_of \
      :scores,
      name: "scores_2007".to_sym,
      partition_key: ->{ "recent, played_at" },
      start_range: [false, "1980-01-01"],
      end_range: [false, "2008-01-01"]

`

`explain select * from scores where recent = false and deleted = false and played_at = DATE '2006-03-03'` - Checks only **scores_2007** partition.

Do you have any Idea if this is doable, or there are certain constraints that don't allow it to be done with 3 keys?

Thank you!

**Comment by rkrage** [comment]
My gut tells me that this is a PostgreSQL limitation, but I'll try to dig into it tonight. Oh, and FYI, in 1.0.0, it's no longer necessary to pass `partition_key` as an option to `create_range_partition_of`. You should only need to specify the key when creating the parent partition via `create_range_partition`.

**Comment by RaresSalcudean** [comment]
I sent an email to PostgreSQL Bug Center, and indeed it is a bug on their side.

The bug can be purely reproduced using Postgres:

```
create table rangep (a bool, b bool, c date) partition by range (a,b,c);

create table rangep1_recent partition of rangep for values from (true,false, '1990-01-01') to (true,false,'2090-01-01');
create table rangep1_deleted partition of rangep for values from (false,true, '1990-01-01') to (false,true,'2090-01-01');
create table rangep1_2019 partition of rangep for values from (false,false, '2019-01-01') to (false,false,'2020-01-01');
create table rangep1_2018 partition of rangep for values from (false,false, '2018-01-01') to (false,false,'2019-01-01');
create table rangep1_2017 partition of rangep for values from (false,false, '2017-01-01') to (false,false,'2018-01-01');

explain select * from rangep where not a and not b and c = '2019-07-10';
```

Answer

> Thanks for making the test case. It is a bug.  There's a problem in
> match_clause_to_partition_key() where because
> match_boolean_partition_clause() returns false for the "NOT b"
> condition when comparing to the first partition key this causes the
> function to return PARTCLAUSE_UNSUPPORTED which causes the calling
> function to not bother trying to match that qual up to any other
> partition key. Effectively, for pruning the WHERE clause is just WHERE
> NOT a AND c = '2019-07-10', so only the rangep1_recent partition is
> pruned.
> 
> I'll look into fixing it. Thanks for the report.

**Comment by rkrage** [comment]
👍 closing this for now.
