### ISSUE TITLE
Feature request: select range partitions by one of date

### ISSUE THREAD

**Issue by piton4eg** [rkrage/pg_party#48]
At first, thanks for the gem!

I have couple ideas, that I hope could make using the gem little easier.

1. For now, it's possible to select partitions by two dates - start date and end date. I guess it would be nice to have them optional, like:
```
Model.partitions(start_date: Date.today) or Model.partitions(end_date: Date.today)
```
Example: I need to find the last record, but not later than today.

2. Maybe it worth to return list of partitions in sorted order. Even more, would be good to allow order from model, like:
```
Model.partitions(order: :asc) or Model.partitions(order: :desc)
```

**Comment by rkrage** [comment]
I guess I'm a little confused about this:

> For now, it's possible to select partitions by two dates - start date and end date.

At the moment, the `partitions` method just returns an array of strings (the names of the currently attached partitions for a given model).

Basically, you're looking for an enhancement to the `partitions` method that would allow you to filter the results in some way? I'll have to dig into the metadata that postgres stores about partitions / partition keys and figure out if there's a generic way to query it

**Comment by rkrage** [comment]
This is the current implementation that pulls partition information: https://github.com/rkrage/pg_party/blob/3e144b48fad222c40d7e1864e4d648b39fbcffea/lib/pg_party/model_decorator.rb#L65-L77

Feel free to investigate this yourself as well!

**Comment by rkrage** [comment]
Gonna close this for now due to lack of context
