### ISSUE TITLE
Partition by ForeignKey?

### ISSUE THREAD

**Issue by mrlevitas** [rkrage/pg_party#52]
Could you clarify if partitioning by foreign key is supported?

I see this example in the ReadMe: 
```
create_list_partition :some_list_records, partition_key: :id do |t|
      t.integer :some_foreign_id
      t.text :some_value
      t.timestamps
end
```

But is it possible to use `partition_key: :some_foreign_id` like so:
```
create_list_partition :some_list_records, partition_key: :some_foreign_id do |t|
      t.references :some_foreign, foreign_key: true
      t.string :name
      t.timestamps
end
```
?

So that if I want a partition per `:some_foreign_id`, could I do something like:
```
SomeForeign.all.map do |foreign|
  create_list_partition_of :some_list_records, name: foreign.name, partition_key: :some_foreign_id, values: [foreign.id]
 end
```
with each partition getting the respective `name` of each foreign record?

**Comment by rkrage** [comment]
That's a great question and I'll have to get back to you. Something like that _might_ be supported in PG 12+

**Comment by mrlevitas** [comment]
I tried this setup and it seems to work (I am running postgres 12.3 though), but I'm not sure if there are hidden problems that can occur in regular usage.

Given the above setup, this spec passes:
```
describe SomeListRecords do
  describe 'partitions by some_foreign' do
    let!(:some_foreign_1) { create :some_foreign }
    let!(:some_foreign_2) { create :some_foreign }

    before do
      [some_foreign_1, some_foreign_2].each do |some_foreign|
        ActiveRecord::Base
          .connection
          .create_list_partition_of(
            :some_list_records, name: some_foreign.name, partition_key: :some_foreign_id, values: [some_foreign.id]
          )
      end
    end

    let!(:some_list_record_1)  { create :some_list_record, some_foreign: some_foreign_1 }
    let!(:some_list_record_2) { create :some_list_record, some_foreign: some_foreign_1 }
    
    let!(:some_list_record_3) { create :some_list_record, some_foreign: some_foreign_2 }

    it 'returns some_foreign_1 records' do
      expect(SomeListRecords.in_partition(some_foreign_2.id).all).to contain_exactly(some_list_record_1, some_list_record_2)
    end

    it 'returns some_foreign_2 record' do
      expect(SomeListRecords.in_partition(some_foreign_2.id).all).to contain_exactly(some_list_record_3)
    end

    it 'has 2 corresponding partitions' do
      expect(SomeListRecords.partitions).to contain_exactly(some_foreign_1.name, some_foreign_2.name)
    end
  end
end
```

**Comment by rkrage** [comment]
Okay, yeah this should totally work. They introduced the ability to define PKs, foreign keys, and indexes on partitioned tables in PG 11. One small note about the above code sample. There are actually helper methods in partitioned model classes that will let you create partitions without directly using `ActiveRecord::Base.connection`. The helpers imply the partition key and figures out what underlying method to call (`create_list_partition_of` vs `create_range_partition_of`). This should probably be documented better.

```ruby
SomeListRecords.create_partition(name: "some_unique_table_name", values: [some_foreign.id])
```

**Comment by mrlevitas** [comment]
awesome, thanks for the response.

**Comment by mrlevitas** [comment]
just fyi, `SomeListRecords.create_partition(name: "some_unique_table_name", values: [some_foreign.id])` didn't work for me:

**Comment by rkrage** [comment]
Huh, that's interesting. What does your `SomeListRecords` class look like?

**Comment by mrlevitas** [comment]
these are the models:
```
class SomeListRecords < ActiveRecord::Base
  list_partition_by : some_foreign_id

  belongs_to : some_foreign
  belongs_to :another_foreign
end
```

```
class SomeForeign < ActiveRecord::Base
  has_many :profiles
  has_many :messages
  has_many :some_list_records
end
```
-------------------------
these are the migrations:
```
    create_list_partition : some_list_records, partition_key: :carrier_id do |t|
      t.string     :uuid, null: false
      t.references :some_foreign, foreign_key: true, index: false
      t.references :another_foreign, foreign_key: true
      t.timestamps null: false
    end



    add_index :some_list_records_template, [:uuid, :some_foreign_Id]
    add_index :some_list_records_template, [:some_foreign_id, :created_at]
```

```
    create_table :some_foreign do |t|
      t.string :name, null: false, unique: true
      t.timestamps null: false
    end
```
--------------------------------------
and these are my factories:
```
FactoryBot.define do
  factory :some_list_records, class: SomeListRecord do
    sequence(:uuid) { |n| 'uuid_' + n.to_s }
    association :some_foreign, factory: :some_foreign
    association :another_foreign, factory: :another_foreign
  end
end
```

```
FactoryBot.define do
  factory :some_foreign, class: SomeForeign do
    sequence(:name) { |n| 'some_foreign' + n.to_s }
  end
end
```

anything pop out?

**Comment by mrlevitas** [comment]
created a sample app that demonstrates this:
https://github.com/mrlevitas/partition-example

hope it helps debugging.

**Comment by rkrage** [comment]
Thanks for putting this together. I have a pretty busy week but can hopefully look into it soon

**Comment by rkrage** [comment]
Sorry it took me so long to look into this. I think this is actually an `rspec` issue. By default, it starts a transaction for each spec and rolls it back afterwards. This is _generally_ fine in most cases where you're just performing inserts, updates, deletes. But when you introduce DDL operations things start to break down.

So by running `ActiveRecord::Base.connection.create_list_partition_of`, I _think_ that was being executed in a separate connection outside of the transaction.

If you'd like to perform DDL in your tests you might want to consider using `database_cleaner` with the `truncation` strategy: https://github.com/rkrage/pg_party/blob/master/spec/spec_helper.rb#L59-L69

It's also possible that truncation is natively supported in `rspec` as well and I'm just out of the loop.

**Comment by rkrage** [comment]
Gonna close this for now, but feel free to open it again if you're still experiencing issues!
