### ISSUE TITLE
rspec tests fail unless using structure.sql

### ISSUE THREAD

**Issue by mrlevitas** [rkrage/pg_party#53]
I noticed that unless I switch from `schema.rb` to `structure.sql`, I get:
```PG::InvalidObjectDefinition: ERROR:  table "x" is not partitioned```

when calling `create_list_partition_of` in rspec.

Is there any way to run tests on partitioned tables without having to switch to `structure.sql`?

**Comment by rkrage** [comment]
Unfortunately, that's a limitation outlined in the README. I imagine supporting `schema.rb` would require some pretty intense  Rails monkey patching. I wasn't super interested in implementing this, as I always use `structure.sql` in my applications. But I'm definitely open to PRs.

**Comment by mrlevitas** [comment]
got it, thanks.
