### ISSUE TITLE
Explanation needed: Are many "partition tables" a problem?

### ISSUE THREAD

**Issue by nhh** [rkrage/pg_party#55]
Hi there,

this question may be a bit too "broad" but i wonder if these "partition tables" can be used for "personal report data".

That means big tables split up in maybe hundreds of "partitioned tables" which belong to several certain users.
(Yearly report for user X, monthly report for user Y and so on)

Are there known drawbacks if a user has, for example 10 partitioned tables?

Is this a use case for "partitioned tables" in postgres?

Thanks in advance!
Niklas

**Comment by rkrage** [comment]
Hey @nhh,

In this example, individual users would have their own partitioned tables? Seems like things could really balloon out of control as more users are added to the system, so I'm not sure I'd recommend that.

It would also be helpful to know what "big" means in this case. With proper indexing, Postgres can comfortably handle tables with hundreds of millions or even billions of rows. I would start simple and implement partitioning only when performance issues start to arise.

**Comment by nhh** [comment]
Hey @rkrage,

Thats exactly what i feel about introducing a partitioned table per user. So i stick with a single giant table for now :)

In my case the data is gathered per minute, for several hundred or eventually thousands of measurements.

I guess my indexing is actually not as proper as it could be, because i am already hitting performance issues with only about 2 million database entries. All of the measurements are time based and belong to a specific service and user.

Introducing pg-party would make sense if i am start to "drop" the realtime data in favor of "grouped" data for a few groups, like yearly, monthly, daily, hourly - right?

Do you have some resources on setting proper time-based indices for postgres? I guess my knowledge is actually to limited to ask the right questions :)

Thank you for your interest and answering my question! :v:
