### ISSUE TITLE
Convert a normal table to partitioned table

### ISSUE THREAD

**Issue by estebansa19** [rkrage/pg_party#56]
Hi, I hope you are doing well. I'm have some performance issues with huge table (millions of records) so I'm interested in convert this table to a partitioned table because it fits perfectly with what we need. ¿Is there a way to alter this table to make it partitioned or is required create another table?

**Comment by rkrage** [comment]
Hi @estebansa19,

I think it depends on your partitioning strategy. This library supports attaching an existing table as a partition, so if you just wanted to start adding newly inserted rows to a fresh partition and leave the existing data alone in one large partition that might be the way to go. To my knowledge, there isn't a great way to chop up an existing table into several partitions (at least it's not something this library supports). If you wanted to go that route, you'd likely have to run some backfill scripts to copy the data into your new partitioned table.

Also, Postgres is _generally_ capable of handling a table with millions of records, so it might be worth looking at query plans to see if adding some indexes would help.

**Comment by rkrage** [comment]
There hasn't been any activity in awhile, so I'm closing this. Feel free to open it again if you still have questions
