### ISSUE TITLE
ActiveRecord doesn't support composite primary keys?

### ISSUE THREAD

**Issue by machty** [rkrage/pg_party#57]
I'm on Rails 5.2 and I see this when I instantiate a record from a partitioned table:

```
WARNING: Active Record does not support composite primary key.

partitioned_inventory_items has composite primary key. Composite primary key is ignored.
```

I've heard that AR doesn't support composite primary keys, but yet pg_party seems to suggest in the README that you use composite primary keys? I'm also wondering how this hasn't already come up in the issues...

**Comment by rkrage** [comment]
It looks like composite primary key support was added very recently with: https://github.com/rkrage/pg_party/pull/54

If I'm being perfectly honest, I haven't been doing a ton of Rails development lately and haven't been keeping up with new features.

@webandtech do you have any context on this one? If Rails truly doesn't support composite primary keys, I'm hesitant to allow them in pg_party migration methods

**Comment by webandtech** [comment]
Support was added to the gem BUT disabled by default via the config option `create_with_primary_key` which defaults to `false`. You are correct that ActiveRecord does not support it out of the box... I had forgot about this and the various workarounds.

For our typical use case we just trick ActiveRecord to use `id` as the primary key and make sure the partition key is used as well in any lookups i.e. `find_by!(id: some_id, partition: 5)` to avoid queries against all partitions.

There is a [`composite_primary_keys`](https://github.com/composite-primary-keys/composite_primary_keys) gem which I have used in the past.

Looking at repos where we're using this today we have actually used an override in the base model class to just trick ActiveRecord to ignore the partition key:

```ruby
# Avoid primary_key errors when using composite primary keys (e.g. id, partition_number)
def primary_key
  return @primary_key if @primary_key

  primary_object_keys = Array.wrap(connection.schema_cache.primary_keys(table_name)) - [partition_key]

  if primary_object_keys.size == 1
    @primary_key = primary_object_keys.first
  elsif connection.schema_cache.columns_hash(table_name).include?('id')
    @primary_key = 'id'
  else
    # table is without a primary key and `id` is not present in the table
    @primary_key = nil
  end
 end
```

@rkrage I think perhaps I should update the README but I think this gem should support creating tables with primary key options supported by Postgres... Rails does not prevent you from creating tables with composite primary keys... it just does not support it fully throughout the ORM. What do you think?

**Comment by webandtech** [comment]
I posted a PR: https://github.com/rkrage/pg_party/pull/58/files to update the README as I agree we shouldn't "recommend" a configuration, especially one which would lead someone to get warnings from ActiveRecord.

**Comment by rkrage** [comment]
Makes sense. I'm onboard. Just left a PR comment
