### ISSUE TITLE
Migration from `partitioned` gem to `pg_party`

### ISSUE THREAD

**Issue by avokhmin** [rkrage/pg_party#69]
Good day.

Does anybody know how to migrate from  https://github.com/fiksu/partitioned to `pg_party`?
We have a super old project and try to update.

The `partitioned` gem uses other schema for partitioned tables, e.g.:
- table `p201511`, schemaname: `my_table_name_partitions`
- table `my_table_name`, schemaname: `public`

Second, the `partitioned` gem doesn't use native PG table partitioning :(

We use partitioning by date.

Thanks,
Aleksei.

**Comment by rkrage** [comment]
Whoops, sorry I haven't been super active on this project. PgParty does have the ability to attach / detach partitions so maybe the migration would involve creating a new native partitioned table and attaching your legacy partitions. It's hard to say without more information, but honestly this feels like more of a question for a DB admin, which I am not 😄
