### ISSUE TITLE
create_range_partition and Ruby 3

### ISSUE THREAD

**Issue by amy-hs** [rkrage/pg_party#74]
Hello! We're in the process of upgrading to Ruby 3, and we're running into an issue with `create_range_partition`:
```
# How we're using it in our DB migration
def up
  create_range_partition(:table_name, partition_key: :created_at, primary_key: [:id, :created_at]) do |t|
    ...
  end
end

# Error that occurs due to the Ruby 3 keyword arguments change
wrong number of arguments (given 2, expected 1; required keyword: partition_key)
```

Looking through the stacktrace, the issue seems to come from this module in `pg_party`:
```
module PgParty
  module Adapter
    module PostgreSQLMethods
      ruby2_keywords def create_range_partition(*args, &blk)
        PgParty::AdapterDecorator.new(self).create_range_partition(*args, &blk)
      end
    ...
  end
end
```

The arguments are coming in as:
```
["table_name", {:partition_key=>:created_at, :primary_key=>[:id, :created_at]}]
```

So that when it bubbles up to the `AdapterDecorator`, it can't parse out the partition key properly:
```
def create_range_partition(table_name, partition_key:, **options, &blk)
  create_partition(table_name, :range, partition_key, **options, &blk)
end
```

At least, that's what I understand it to be doing? Are we using `create_range_partition` incorrectly, or should there be a fix? Thanks so much!

**Comment by amy-hs** [comment]
👋 @justinperkins We are also on `1.6.0`. Ah, so you're not actually using the `create_range_partition` method but just using `create_partition`. Let me give that a try and see how it goes. Thank you!

**Comment by amy-hs** [comment]
Hmm, the `create_partition` didn't work for us. Any other thoughts?

**Comment by rkrage** [comment]
It looks like you're calling that method correctly... What specific version of Ruby and Rails are you using?

**Comment by amy-hs** [comment]
> It looks like you're calling that method correctly... What specific version of Ruby and Rails are you using?

👋 We're on Rails 6.0.6.1 and Ruby 3.0.6

**Comment by amy-hs** [comment]
I'm going to close this for now 👍 I think we might have had the gem misconfigured somehow in an area of our code (still digging into it, but seems likely on our end). Thanks all for the help!

**Comment by amy-hs** [comment]
For anyone that's curious, it was a conflict with `strong_migrations` that was causing the issue.
